version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    command: --init-file /docker-entrypoint-initdb.d/initdb.sql
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8088:3306"
volumes:
  db_data:
