CREATE DATABASE IF NOT EXISTS CUSTOMER;

USE CUSTOMER;

CREATE TABLE IF NOT EXISTS ADDRESS_INFO (
  COD_ID INT(11) NOT NULL AUTO_INCREMENT,
  DES_STREET VARCHAR(255) DEFAULT NULL,
  DES_NUMBER VARCHAR(255) DEFAULT NULL,
  DES_COMPLEMENT VARCHAR(255) DEFAULT NULL,
  DES_DISTRICT VARCHAR(255) DEFAULT NULL,
  DES_CITY VARCHAR(255) DEFAULT NULL,
  DES_POSTAL_CODE VARCHAR(255) DEFAULT NULL,
  DES_COUNTRY VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (COD_ID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=10001;

CREATE TABLE IF NOT EXISTS CUSTOMER_INFO (
  COD_ID INT(11) NOT NULL AUTO_INCREMENT,
  COD_ADDRESS_ID VARCHAR(255) DEFAULT NULL,
  DES_NAME VARCHAR(255) DEFAULT NULL,
  TYP_DOCUMENT_TYPE VARCHAR(255) DEFAULT NULL,
  DES_DOCUMENT_CODE VARCHAR(50) DEFAULT NULL,
  DES_EMAIL VARCHAR(255) DEFAULT NULL,
  DES_PHONE VARCHAR(255) DEFAULT NULL,
  DES_STATUS VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (COD_ID),
  FOREIGN KEY (COD_ADDRESS_ID) REFERENCES ADDRESS_INFO(COD_ID)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=10001;
